{{- if .Values.tls.public.trustBundle.enabled }}
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: {{ default (printf "%s-public-ca" (include "hydradb.fullname" .)) .Values.tls.public.trustBundle.name }}
  labels:
    {{- include "hydradb.labels" . | nindent 4 }}
spec:
  sources:
    - secret:
        name: {{ default (include "hydradb.publicTlsSecretName" .) .Values.tls.public.trustBundle.sourceSecretName }}
        key: {{ .Values.tls.public.trustBundle.sourceSecretKey }}
    {{- with .Values.tls.public.trustBundle.additionalSources }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  target:
    configMap:
      key: ca.crt
      metadata:
        labels:
          app.kubernetes.io/component: hydradb-client-trust
    namespaceSelector:
      {{- toYaml .Values.tls.public.trustBundle.namespaceSelector | nindent 6 }}
{{- end }}
