//! Safe Rust names for libcypher-parser's exported AST type globals.

use libcypher_parser_sys as sys;

#[derive(Clone, Copy, Debug)]
pub(super) enum AstKind {
    ApplyAllOperator,
    ApplyOperator,
    BinaryOperator,
    Collection,
    Comparison,
    Create,
    Delete,
    False,
    Float,
    FunctionName,
    Identifier,
    Integer,
    Label,
    Map,
    Match,
    Merge,
    MergeProperties,
    NodePattern,
    Null,
    OrderBy,
    Parameter,
    Pattern,
    PatternPath,
    PropertyOperator,
    PropertyName,
    Query,
    Range,
    RelationshipType,
    RelationshipPattern,
    Remove,
    RemoveLabels,
    RemoveProperty,
    Return,
    Set,
    SetAllProperties,
    SetLabels,
    SetProperty,
    SortItem,
    Statement,
    String,
    True,
    UnaryOperator,
    Union,
    Unwind,
    With,
}

impl AstKind {
    pub(super) fn as_ffi(self) -> sys::cypher_astnode_type_t {
        // SAFETY: cypher-parser.h declares these as extern const globals.
        // The linked library supplies initialized, immutable type identifiers;
        // reading one copies its value and does not access an AST node.
        unsafe {
            match self {
                Self::ApplyAllOperator => sys::CYPHER_AST_APPLY_ALL_OPERATOR,
                Self::ApplyOperator => sys::CYPHER_AST_APPLY_OPERATOR,
                Self::BinaryOperator => sys::CYPHER_AST_BINARY_OPERATOR,
                Self::Collection => sys::CYPHER_AST_COLLECTION,
                Self::Comparison => sys::CYPHER_AST_COMPARISON,
                Self::Create => sys::CYPHER_AST_CREATE,
                Self::Delete => sys::CYPHER_AST_DELETE,
                Self::False => sys::CYPHER_AST_FALSE,
                Self::Float => sys::CYPHER_AST_FLOAT,
                Self::FunctionName => sys::CYPHER_AST_FUNCTION_NAME,
                Self::Identifier => sys::CYPHER_AST_IDENTIFIER,
                Self::Integer => sys::CYPHER_AST_INTEGER,
                Self::Label => sys::CYPHER_AST_LABEL,
                Self::Map => sys::CYPHER_AST_MAP,
                Self::Match => sys::CYPHER_AST_MATCH,
                Self::Merge => sys::CYPHER_AST_MERGE,
                Self::MergeProperties => sys::CYPHER_AST_MERGE_PROPERTIES,
                Self::NodePattern => sys::CYPHER_AST_NODE_PATTERN,
                Self::Null => sys::CYPHER_AST_NULL,
                Self::OrderBy => sys::CYPHER_AST_ORDER_BY,
                Self::Parameter => sys::CYPHER_AST_PARAMETER,
                Self::Pattern => sys::CYPHER_AST_PATTERN,
                Self::PatternPath => sys::CYPHER_AST_PATTERN_PATH,
                Self::PropertyOperator => sys::CYPHER_AST_PROPERTY_OPERATOR,
                Self::PropertyName => sys::CYPHER_AST_PROP_NAME,
                Self::Query => sys::CYPHER_AST_QUERY,
                Self::Range => sys::CYPHER_AST_RANGE,
                Self::RelationshipType => sys::CYPHER_AST_RELTYPE,
                Self::RelationshipPattern => sys::CYPHER_AST_REL_PATTERN,
                Self::Remove => sys::CYPHER_AST_REMOVE,
                Self::RemoveLabels => sys::CYPHER_AST_REMOVE_LABELS,
                Self::RemoveProperty => sys::CYPHER_AST_REMOVE_PROPERTY,
                Self::Return => sys::CYPHER_AST_RETURN,
                Self::Set => sys::CYPHER_AST_SET,
                Self::SetAllProperties => sys::CYPHER_AST_SET_ALL_PROPERTIES,
                Self::SetLabels => sys::CYPHER_AST_SET_LABELS,
                Self::SetProperty => sys::CYPHER_AST_SET_PROPERTY,
                Self::SortItem => sys::CYPHER_AST_SORT_ITEM,
                Self::Statement => sys::CYPHER_AST_STATEMENT,
                Self::String => sys::CYPHER_AST_STRING,
                Self::True => sys::CYPHER_AST_TRUE,
                Self::UnaryOperator => sys::CYPHER_AST_UNARY_OPERATOR,
                Self::Union => sys::CYPHER_AST_UNION,
                Self::Unwind => sys::CYPHER_AST_UNWIND,
                Self::With => sys::CYPHER_AST_WITH,
            }
        }
    }
}
